Models/ErrorViewModel.cs
namespace QRCodeGen.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using QRCodeGen.Models;

namespace QRCodeGen.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/QRCodeController.cs
using QRCoder;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using System.Drawing.Imaging;

namespace QRCodeGen.Controllers;

public class QRCodeController : Controller
{
    private readonly ILogger<QRCodeController> _logger;

    public QRCodeController(ILogger<QRCodeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    
    private static Byte[] BitmapToByteArray(Bitmap bitmap)
    {
        using (var stream = new MemoryStream())
        {
            bitmap.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
            return stream.ToArray();
        }
    }

    public IActionResult Generate(string payload)
    {
        QRCodeGenerator qrCodeGenerator = new QRCodeGenerator();
        QRCodeData qrCodeData = qrCodeGenerator.CreateQrCode(payload, QRCodeGenerator.ECCLevel.Q);
        QRCode qrCode = new QRCode(qrCodeData);

        using (MemoryStream stream = new())
        {
            using (Bitmap bitmap = qrCode.GetGraphic(20))
            {
                bitmap.Save(stream, ImageFormat.Png);
                ViewBag.QRCodeImage = "data:image/png;base64," + Convert.ToBase64String(stream.ToArray());
            }
        }
        return View("Index");
    }
}

Views/Home/Index.cshtml
<html>
<head>
    <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link rel="stylesheet" href="Index.cshtml.css">
    @{
        ViewData["Title"] = "Home Page";
    }
    <link rel="stylesheet" href="Index.cshtml.css">
</head>
    <body>
    <div class="text-center">
            <h1 class="display-4">Welcome To QRCodeGen</h1>
        <p class="mt-5">A simple web website that makes QR codes very easy for you</p>
        <div>
            <div class="d-block text-center">
                <img src="~/QRCode.svg" class="img-fluid" alt="">
            </div>
            <a class="btn btn-secondary btn-lg" asp-controller="QRCode" asp-action="Index">Click here to get started</a>
        </div>
        </div>
    </body>
</html>

Views/QRCode/Index.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="Index.cshtml.css" />
    @{ ViewBag.title = "QR code - Generator"; ViewBag.layout = "_Layout"; }
  </head>
  <body>
    <h1 class="display-3 text-center mt-5">QR Code Generator</h1>

    <div class="text-center box">
      <form asp-action="Generate" method="post" class="mt-3">
        <input
          type="text"
          required
          name="payload"
          class="p-3 pt-4 no-border-top-right-left no-outline text-input"
          placeholder="Enter the text to encode" />
        <div class="text-center">
          @{
            if (ViewBag.QRCodeImage != null)
          {
            <img class="img-fluid" src="@ViewBag.QRCodeImage" alt="qr code" />
          }
            else
          {
            <img
              class="img-fluid align-self-center"
              src="~/QRCode.svg"
              alt="qr code" />
          }
        }
        </div>
        <input
          class="btn btn-primary rounded-extra"
          type="submit"
          value="Generate" />
      </form>
    </div>
  </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QRCodeGen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link
      rel="stylesheet"
      href="~/QRCodeGen.styles.css"
      asp-append-version="true" />
  </head>
  <body>
    <header>
      <nav
        class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
          <a
            class="navbar-brand"
            asp-area=""
            asp-controller="Home"
            asp-action="Index"
            >QRCodeGen</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target=".navbar-collapse"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div
            class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
              <li class="nav-item">
                <a
                  class="nav-link text-dark"
                  asp-area=""
                  asp-controller="Home"
                  asp-action="Index"
                  >Home</a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link text-dark"
                  asp-area=""
                  asp-controller="QRCode"
                  asp-action="Index"
                  >QRCode</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <main role="main" class="pb-3">@RenderBody()</main>
    </div>

    <footer class="border-top footer text-center text-muted">
      <div class="container">
        &copy; 2023 - QRCodeGen - Made with
        <img src="heart_833472.png" alt="Heart" /> By
        <a class="text-secondary" href="https://github.com/victorchiaka"
          >Victor Chiaka</a
        >
      </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- to load my javascript file -->
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
  </body>
</html>